- .github/workflows/push.yml
With @eaddingtonwhite help, moved the PyPI auth token to the org level secret.
Since secret names need to be unique at the org level, this repo's secret name got updated to `CLIENT_PROTO_PYPI_TOKEN`.
> chore: Update secret variable name for PyPI auth token

- javascript/package-lock.json
- javascript/package.json
Updated `@grpc/grpc-js` version to the latest, `1.5.10` to match the version in the JS SDK.
This is a part of the debugging task (https://github.com/momentohq/client-sdk-javascript/issues/49).
> chore: Update `@grpc/grpc-js` version to the latest

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- javascript/package-lock.json
- javascript/package.json
Due to the sign in issue mentioned [here](https://gomomento.slack.com/archives/C01AC7JT370/p1648234227968489), publishing the package with `@gomomento/generated-types`.
Naming discussion happened [here](https://gomomento.slack.com/archives/C037XLHFC79/p1648244643528289).
> chore: Publish package to npm with a new scope name `@gomomento/generated-types`

- proto/controlclient.proto
In the create signing key response, we also need to include algo for our sdk to be able to use the key.  Instead of returning separate fields, we'll be using jwk(JOSN web key), which is a json data structure that represents a cryptographic key. 
https://datatracker.ietf.org/doc/html/rfc7517#section-1.1
Note that expiry is not a supported parameter in jwk.  We'll be returning this field separately.
> feat: use a single jwk to encapsulate key id and algo along with the key

- proto/cacheclient.proto
Fixes https://github.com/momentohq/client_protos/issues/41
Changes `ttl_milliseconds` so that consumers (like Java) don't overflow values
> chore: change ttl_milliseconds type to uint64

- proto/httpcache.proto
Looks like we also need to change this type to `uint64` so that our HttpClient is also compatible
> chore: also update the HttpSetRequest to use uint64

- proto/cacheclient.proto
- rust/Cargo.toml
Closes #50 
Add the rpc method declarations for DictionaryGet, DictionaryGetAll DictionarySet and the associated request and response messages. Terminology:
- dict, dictionary: a data structure that supports key-based indexing
- dictionary name: the name of a dictionary stored in momento (ie the cache key for the dictionary)
- dictionary key: a key to index into a dictionary
- dictionary value: the value corresponding to a key in a particular dictionary (ie `dictionary_value = dictionary_name.get(dictionary_key)`)
The following summarizes the methods:
- DictionaryGet: request the dictionary value for the dictionary key `dictionary_key` from a dictionary `dictionary_name`. The response message is identical to that of `_GetResponse`
- DictionaryGetAll: request the entire dictionary …
> feat: Add proto declarations for dictionary.

- .github/workflows/pull_request.yml
- proto/auth.proto
Will enable some more convenient client-side heuristics around
session refreshing.
> chore: add validity time to logged in message

- proto/cacheclient.proto
Change DictionaryGetRequest to support any number of keys in the
request. Similarly modify DictionaryGetResponse to return multiple
values, each with the cache status (HIT, MISS, etc) and cache body.
> feat: Support variadic keys in DictionaryGet

- proto/cacheclient.proto
Per discussions, data structure `set` operations will always include a
TTL and a flag to refresh the TTL (or not).
We include the TTL to be consistent with our system design: all items
in the cache must have a TTL.
Because users may want different behavior when creating a data
structure vs updating a data structure, we also include the flag
`refresh_ttl`. The intention is that when a user creates a data structure,
`ttl_milliseconds` is applied. When a user updates a data structure,
if the flag `refresh_ttl` is `true`, then the TTL will be refreshed to
`ttl_milliseconds`. Otherwise when `refresh_ttl` is `false` on an
update, the remaining TTL will be left as-is.
> feat: Add TTL & refresh TTL fields to _DictionarySetRequest message.

- proto/cacheclient.proto
- proto/controlclient.proto
This PR aligns the gRPC generated code with the C# package published
to NuGet. The C# package and assembly are "Momento.Protos" and
"Momento.Protos.dll" respectively.
This places the cache client generated code under the namespace
`Momento.Protos.CacheClient` and the control client code under the
namespace `Momento.Protos.ControlClient`.
> feat: scope C# cache and control protos in namespaces

- proto/cacheclient.proto
As per our discussion this morning, we want the push/pop operations to operate on a single value rather than multiple values. We already do that for the list pop apis. This PR updates the `ListPushFront` and `ListPushBack` api requests to take a single value as an input.
> fix: take a single value as input for list push apis

- proto/cacheclient.proto
This adds an optional parameter to `ListPushFront` and `ListPushBack`
requests to maintain a list length invariant. Should the push
operation make the list exceed the given length, the excess is trimmed
from the opposite end of the list.
Closes #81
> feat: add truncate option to list push

- csharp/Momento.Protos.csproj
The C# generator allows the option to generate client code vs server
code vs both. By default it generates both. Since the clients only
need the client code, this change narrows the build to only generate
those.
> fix: only generate gRPC client code for C#

- proto/cacheclient.proto
For `ListPush` We use the nouns "Front" and "Back" to refer to the
beginning and end of the list respectively. In the previous commit, in
the context of truncate, we used the nouns "Head" and "Tail". That
introduced extra vocabulary to refer to exactly the same
concepts. This commit renames "Head" and "Tail" to "Front" and "Back"
for consistency.
> fix: make truncate_*_to_size nomenclature consistent with ListPush*

- proto/cacheclient.proto
This adds the list length to `ListPushFrontResponse` and
`ListPushBackResponse`. This corresponds to the length of the list
just after the request's value is pushed.
> feat: list push returns the length of the list post-push

- proto/cacheclient.proto
This adds the RPC, request, and response messages for `DictionaryIncrement`. The response includes a `status` field to indicate whether the operation was successful or not.
An increment operation (`DictionaryIncrement` or regular `Increment`) may fail if the stored value does not parse to a number. Other errors to consider including are integer overflow or integer underflow.
> feat: add `DictionaryIncrement`

- proto/cacheclient.proto
We will propagate increment failures with exceptions. For incrementing a value that is not an integer, we will use gRPC status code `FAILED_PRECONDITION`.
> fix: remove increment status code

- csharp/Momento.Protos.csproj
We are changing our target framework to netstandard2.0. With this we will support some older .NET Framework versions.
Work towards https://github.com/momentohq/client-sdk-dotnet/issues/164
> feat: dotnet target framework netstandard2.0

- javascript/package-lock.json
- javascript/package.json
We have encountered some minor issues with grpc-js running in
AWS Lambda environment.  We're a little out of date on our
grpc dependency so this brings us up to the latest.  This
didn't fix the AWS lambda issues, but does include some bug
fixes and updates that seem worth picking up.  See release notes
here:
https://github.com/grpc/grpc-node/releases
> chore: update grpc-js library to latest

- proto/controlclient.proto
The RPC will allow callers to flush all the data from a given cache. Once this operation is invoked on a cache all the data prior to invoking the operation will not be available to the callers.
> feat: Add an RPC to support flushing caches

- proto/cacheclient.proto
This commit adds a basic Ping RPC.  Empty request payload, empty
response payload.  This can be used to ensure that the client/server
connection is healthy, or, for clients that don't provide a mechanism
to eagerly establish the connection, this gives us a way to do it
without impacting cache metrics for the client.
> feat: add "Ping" rpc, for use in ensuring connections are active

- proto/cacheclient.proto
The main cache service requires a "cache" header with a valid
cache name on every request.  This doesn't work well for the
Ping RPC because we won't necessarily know a cache name (and we
really don't need to know one) at the time we issue the request.
Rather than hacking a bunch of special case logic into the
already-fairly-complex auth interceptor for the cache service,
this moves the ping RPC to a separate service where we can
run without those requirements.
> feat: move ping RPC to separate service

- proto/cacheclient.proto
Add proto definitions for rpc, request, and response for `Increment`.
`Increment` takes a key, an integer by which to increment by (can be negative to decrement), and a ttl. If the key does not already exist, it initializes it at 0.
The `Increment` operation maybe may fail if the stored value (which is stored as a string) does not parse to a number. Currently this error will surface as an `Unavailable` error; in my opinion in order for this API to be usable we will want to make sure we surface the full error.
> feat: Add Increment API

- proto/cachepubsub.proto
For preview and development, here is a possible definition for a pubsub feature with Momento caches.
A topic lives within a Momento cache. Using the Pubsub service, users can subscribe and publish to topics. Topics are multicast message relays. They are lossy, but they try to let you know when you might have missed something.
> feat: add pubsub proto definitions

- rust/build.rs
- rust/src/lib.rs
Enable generated code for the pubsub messages in rust.
> feat: add pubsub definitions to rust package

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- install_protoc.sh
- rust/Cargo.lock
- rust/Cargo.toml
* Update to the current release of tonic and friends
* Update install_protoc script to not leave garbage in the repo directory on github
* Add install_protoc to rust build steps - new tonic doesn't bundle it anymore
> chore: update rust dependencies

- proto/cacheclient.proto
A sorted set is a collection of elementes ordered by their associated scores.
This PR introduces basic operations to start of supporting sorted sets.
Here is the notion doc for these protos https://www.notion.so/momentohq/Sorted-Sets-5898891409fe4dd88c053bf26ab1d62f
> feat: Add RPCs to support sorted sets

- proto/cacheclient.proto
renames `elemnt` to `element` for sorted set remove elements request
removes `unknown` as a valid option for when fetching a sorted set
https://gomomento.slack.com/archives/C03HUJ5GPAB/p1674774391650909
> fix: remove unknown as valid order option, fix typos

- .gitignore
- proto/cachepubsub.proto
A tool for helping to make long-lived subscriptions to low-rate
topics.
> chore: add heartbeats to topic subscriptions

- proto/cacheclient.proto
Adds an optional Order enum to the SortedSetRank Request. Given an element whose rank needs to be determined, the new ordering parameter determines how the sorted set will be ordered when looking for an element's presence and its rank.
When Ascending order is specified the rank of the element will be its index when the sorted set scores are orderd from low to high. For descending order, the rank of the element is its index when the sorted set scores are ordered from high to low.
> feat: Add ordering for Sorted Set Rank operation

- proto/controlclient.proto
This pr adds a new api to the control plane to generate an api token/refresh token for users to recieve tokens that have an expiration date.
signing up via the cli will look something like
```
momento token generate --endpoint <endpoint> --expiration 30d
```
it will return
```
{
"api_token": <JWT>,
"refresh_token": <refresh token>,
"endpoint": "cell-4-us-west-2.a.prod.momentohq.com",
"valid_until": <epoch seconds when token expires> 
}
```
> feat: add protos for generating secure tokens

- proto/controlclient.proto
After a back and forth, we have decided to use oneof when generating api tokens, to determine if a token expires or not. Previously, we were going to have `valid_for_seconds = 0` to mean that the token would never expire. This change just makes it much more explicit
> feat: use oneof to determine if token has expiry

- proto/auth.proto
- proto/cacheping.proto
A couple proto files were mising the `go_package` option. We keep having to put it back when copying the protos to Go.
> fix: Add missing go_package options.

- proto/cacheclient.proto
Adds protocols for a KeyExists API, which can be used to query whether keys exist or not
> chore: Adding protos for KeyExists

- proto/cacheclient.proto
Adds new API UpdateTtl.
This API allows for setting the TTL for a given key to a specified value.
This can be performed unconditionally, or optionally predicated on one of the following conditions:
- The new TTL would be an increase compared to the existing TTL
- The new TTL would be a decrease compared to the existing TTL
The new API returns a response indicating whether the key was present, and if so, whether the new TTL was applied.
> feat: add UpdateTtl API

- .github/workflows/push.yml
Add a job that detects changes since the last commit and currently outputs whether the protos and java directories have changed.
Make the publish_java job conditional on either protos or java changing. This will prevent a change to another language's code from making a redundant release, but it means not every version increment will have a corresponding java release.
> feat: add change detection so releases can be conditional

- javascript-web/.gitignore
- javascript-web/generate_protos.sh
- javascript-web/index.ts
- javascript-web/package.json
- javascript-web/tsconfig.json
This change is the same as https://github.com/momentohq/client-protos/pull/157, but for the grpc-web sdk. We no longer are bundling the `.ts` files in the package, and just bundling the `.d.ts` and `.js` files
> fix: remove ts files from bundled code for js-web

- javascript-web/generate_protos.sh
This commit adds `cachepubsub.proto` into the `generate_protos.sh` script.
> chore: generate code for pubsub

- proto/auth.proto
This pr allows us to assign specific permissions to an auth token. v1 api tokens created without this `permissions` claim will be treated as `SuperUser` tokens with full permissions. Eventually, we will probably add additional restrictions to support more granular permissions
```
permissions: {
cache: {
role: readwrite
[future stuff]
key: base64?,
key_utf8: string?,
key_hash: sha1?,
apis: ...
},
topic: {
role: readwrite,
[future stuff]
topic: "if this is here it's limited to this topic"
}
}
```
We will also add more roles in the future. MVP is to get a token that has data plane read/write access, so it is currently the only role we need. More details can be found in the notion doc https://www.notion.so/momentohq/Authz-67866217f45a4f3dbaf4c89cade335e9
> feat: add permissions model to the auth token request proto

- README.md
Because the client protos Java library is on Maven Central, we fill in
the remaining TODO.
> docs: add link to Java artifact on Maven Central

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- python/.gitignore
- python/CONTRIBUTING.md
- python/Makefile
- python/poetry.lock
- python/pyproject.toml
- python/run-protoc.sh
There is an incompatiblity between code generated with `grpcio-tools>=1.48.2`
and earlier versions. The later versions of `grpcio-tools` use
`python-protobuf>=3.20`, which includes import statements that
earlier versions do not have. Users with code pinned to `python-protobuf<3.20`
cannot use our SDK. Worse, they will only find out with a runtime exception.
This change compiles the protos using both versions, a pre-3.20
version of `grpc-tools` and version 4 (which is backwards compatible
through 3.20). We bundle both versions, but dynamically import the
correct one in the `momento_wire_types` package top-level init file.
Because of this, a small adjustment is needed to consuming code. We
have to slightly modify the import statements. See `run-protoc.sh` for
an example.
To test, I have …
> feat: support python-protobuf < 3.20

- .github/workflows/push.yml
per the comment, this is an attempt to make cargo publish actually
pick up our generated source _without_ also making that generated
source either [1] dependent on developer protoc installations or [2]
vulnerable to easy git commit -a mistakes.
> fix: remove gitignore during rust publish

- javascript-web/package.json
- javascript/package.json
I think we need to define this as well to make it show up on npm registry.
> chore: fix license in package.json

- javascript/package-lock.json
- javascript/package.json
Features/fixes that come with this upgrade
- Ensure status and error events are consistently emitted asynchronously 
- Fix a memory leak that could result from a specific pattern of recursive function calls
- Fix missing transport trace logs
- Disallow pick_first LB policy as the direct child of an outlier_detection LB policy
> feat: bump grpc js to version 1.8.17

- javascript-web/README.md
- javascript-web/generate_protos.sh
- javascript-web/package-lock.json
- javascript-web/package.json
This is a joint effort between @cprice404  and me to unblock Cloudflare.
Using the websdk in Cloudflare workers gives this error
```
service core:user:momento-cloudflare-worker-http: Uncaught Error: EvalError: Code generation from strings disallowed for this context
```
- Changes to the `generate_protos.sh` script to support running `npm run build` on my mac and fixing permission errors when downloading the plugin
- Temporarily edit the proto files to remove package declarations from proto files to avoid runtime errors like below, which is similar to [this issue](https://github.com/protocolbuffers/protobuf-javascript/issues/40) / [tentative fix](https://github.com/protocolbuffers/protobuf/pull/8696/files#diff-ca4e383959a191d3a6fe7fd0a7494ef6bfad4935bab6788553f7cab9ca8666e1)
```
Test suite …
```
> fix: Use commonjs_strict import_type to avoid Functions in generated code

- javascript/package-lock.json
- javascript/package.json
This includes the following changes [from usptream](https://github.com/grpc/grpc-node/releases):
* Implement channel idle timeout and the channel option grpc.client_idle_timeout_ms (#2471)
* Implement gRFC A62: pick_first: sticky TRANSIENT_FAILURE and address order randomization (#2511)
* Fix premature leaving of context due to improper Http2ServerCallStream handling (#2501 contributed by @CedricKassen)
* Add channel option grpc-node.tls_enable_trace to enable Node TLS tracing (#2507)
* Cancel deadline timer on server when call is cancelled (#2508)
* Added grpc.experimental.createResolver
* Fix propagation of UNIMPLEMENTED error messages (#2528)
* Fix a crash when the channel option grpc.keepalive_permit_without_calls is set (#2519)
* Update keepalive behavior to more correctly handle …
> feat: update grpc-js to 1.9

- .github/workflows/push.yml
- java/build.gradle.kts
Stop generating google common protos. A customer is getting conflicts because they are colliding with those in the proto-google-common-protos dependency.
Change java artifact developer to the generic momento dev to match the java SDK.
Temporarily disable conditional releases of the java protos and add debug statements because java appears to never be released.
> fix: Remove self-generated google common protos

- proto/auth.proto
Two changes
- New write only option for Cache and Topic roles
- You can now specify a per cache item permissions, either by matching key, or key prefix
For full design info https://www.notion.so/momentohq/Fine-Grained-Access-Control-at-Cache-Item-granularity-89be02447a7e41689f17e3e750162e54
> feat: New cache item selector for per key permissions and role for write only

- proto/vectorindex.proto
Our convention is to prefix message names with an underscore to not pollute a
user's IDE autocomplete. Because our SDKs will publish
response types with names identical or similar to the names in the
protos, we want to distinguish the protobuf-generated names from names
in the SDK. Our way of doing this is prefixing the protobuf message
names with an underscore.
> refactor: prefix messages with underscore in vector protos

- proto/controlclient.proto
The previous version had a level of indirection between the list
indexes response and the index name. While that could allow for more
detail in the future, that detail belongs in a "describe index" rpc
and not "list indexes".
> refactor: list indexes should return a list of index names

- proto/controlclient.proto
Customers don't have a way to know what their current limits are, this exposes them in the proto so that we can vend that infomration
> feat: include cache and topic limits in _ListCachesResponse

- proto/vectorindex.proto
For v0 we are going with plain add instead of upsert. Add will allow
users to insert items into their index, but will not do primary key
checks (unlike normal inserts).
> feat: vector index upsert rename to add

- proto/vectorindex.proto
This PR adds an RPC to delete items from the vector index by id. The
semantics are to delete any items from the index with an id in the provided list.
> feat: vector index delete item rpc

- proto/leaderboard.proto
A first step toward a leaderboard offering, I've documented and
translated the internal proposal to a grpc protocol buffers spec.
This isn't connected to any client languages yet; those can be
opted in as we add support and implement the service.
> chore: Add leaderboard definitions

- proto/leaderboard.proto
Related to [#468](https://github.com/momentohq/dev-eco-issue-tracker/issues/468), Leaderboard APIs in the JS SDK.
Added the JS_TYPE annotation to convert uint64 IDs to JavaScript strings. This will prevent loss of precision when converting from protos to JavaScript variables. In the JS SDK, we can convert strings to the appropriate ID type (`bigint`).
> fix: add js-type string annotation to leaderboard uint64 id fields

- proto/leaderboard.proto
Related to [#468](https://github.com/momentohq/dev-eco-issue-tracker/issues/468), Leaderboard APIs in the JS SDK.
Added the JS_TYPE annotation to convert _all_ uint64 fields to JavaScript strings. This will prevent loss of precision when converting from protos to JavaScript variables. In the JS SDK, we can convert strings to the appropriate type (`bigint`).
Follow up to #211 which added the annotation to only the element ID fields.
> fix: add jstype string annotation to all uint64 leaderboard proto fields

- python/run-protoc.sh
In the previous version of `python/run-protoc.sh`, we selectively
edited import statements for `extensions_pb2`. With the prior addition
of `permissionmessages`, the package is broken. We need to edit those
as well.
In order to avoid this in the present and future, we generalize the
edits to all pb2 import statements in our generated code.
> fix: edit python generated pb2 import statements in general

- proto/vectorindex.proto
Expands vector index item metadata value types to allow not just
string but:
- integer (int64)
- double (64-bit precision float)
- boolean
- list of strings
These values cover commonly used metadata types.
> feat: add more vector index item metadata value types

- proto/vectorindex.proto
Factor out NoScoreThreshold message - it is defined twice in vectorindex proto
> chore: factor out NoScoreThreshold in vectorindex proto

- proto/webhook.proto
We need to add `secret_string` as part of the response for `_ListWebhooksResponse`
Options
1. First commit, add optional `secret_string` to `_Webhook`, this message is used in `_PutWebhookRequest` and `_ListWebhooksResponse`, so might be a little odd/confusing that a secret string can be supplied on put webhook request.
2. Second commit, wrapper for webhook and secret_string, `_WebhookWithSecret` for `_ListWebhooksResponse`
```
message _Webhook {
_WebhookId webhook_id = 1;
string topic_name = 2;
_WebhookDestination destination = 3;
}
message _WebhookWithSecret {
_Webhook webhook = 1;
string secret = 2;
}
message _ListWebhooksResponse {
repeated _WebhookWithSecret webhook = 1;
}
> feat: return secret_string along in webhook body for listResponse

- proto/vectorindex.proto
The SearchHit and SearchAndFetchVectorHit structures currently include
a distance field, which is misleading and inconsistent with our naming
conventions. To clarify:
(1) Our Search RPCs utilize a score_threshold to filter results,
implying the evaluation of scores rather than distances.
(2) The term distance suggests that a lower value is preferable,
whereas our system employs similarity metrics where a higher value
signifies better similarity. For example, cosine similarity is a
common metric we use, where a higher score indicates greater
similarity.
To avoid confusion and maintain consistency, we are renaming the
distance field to score. This change is a simple renaming and does not
alter the representation on the wire, ensuring that existing
integrations remain functional.
> chore: mvi - change distance field to score to align with similarity

- proto/controlclient.proto
Previously the list indexes RPC only returned a list of index
names. This PR modifies this to return a list of index detail
containing index name, num dimensions, and similarity metric.
We also factor out the similarity metric message from the
`CreateIndexRequest` since it is common to create index, list indexes,
and (in the future) describe index.
Because the service is in early beta we have carefully weighed
changing this and have agreed the earlier the better.
> feat: add detail to MVI list indexes RPC

- proto/vectorindex.proto
Rename `getItemBatch` to `getItemMetadataBatch` and `getItemAndFetchVectors` to `getItemBatch`
> chore: rename get item apis

- proto/vectorindex.proto
This feature will filter the search results based on the expression user provided. We support `EQUALS`, `AND`, `OR`, `NOT`, `>`, `>=`, `<`, `<=` and `LIST_CONTAINS` for now.
> feat: search filter expression

- proto/vectorindex.proto
In the future we might support more than just list of string. Therefore, changing the value type to be `oneof`.
> chore: expand list contain value type

- proto/auth.proto
This one is pretty straightforward - adds a single optional string field to the API for generating API Keys, which will eventually be displayed when managing API Keys, allowing users to use this field for notes/names/etc to distinguish keys.
> feat: add optional description field when generating API Keys

- .github/workflows/push.yml
Automatically complete the sonatype release process. I've verified that the produced artifact is releasable and have manually approved a release.
> chore: automatically release kotlin protos

- proto/leaderboard.proto
We have completely migrated to using the f64 score field in SDKs and canaries. We can now safely more the f32 score field to reserved.
> chore: moving f32 score field to reserved

- proto/vectorindex.proto
This adds a new MVI filter expression type to filter by ID. The
expression allows a user to specify a set of IDs. An item satisfies
the expression if the item id appears in the set.
> feat: add mvi filter expression to filter by item id

- proto/vectorindex.proto
This PR adds a filter field for the `get item batch`, `get item
metadata batch`, and `delete item batch` RPCs. Currently we allow
users to select items by id. Now that we have an `_IdInSetExpression`
filter expression, users may use that select purely by ID. Otherwise
they may use a more general filter expression.
Until we migrate users to newer clients, we will support both methods
of selecting items: by a list of ids (previous version) and by filter
expression (new version). Once they have migrated we will change the
ids field to reserved.
> feat: support filters for mvi get items and delete items

- javascript/package-lock.json
- javascript/package.json
gRPC 1.9.14 release had a couple fixes relevant to issues we were seeing with reconnections:
- https://github.com/grpc/grpc-node/issues/2620
- https://github.com/grpc/grpc-node/pull/2643
- https://github.com/grpc/grpc-node/pull/2644
> chore: bump gRPC versions

- proto/cacheclient.proto
- proto/cachepubsub.proto
- proto/common.proto
- proto/leaderboard.proto
This commit refactors the `Unbounded` and `Empty` messages out to `common.proto`. This was motivated by build failures in the golang SDK, where the multiply declared messages were flagged as having been redefined because all messages live in the same package namespace.
> chore: move common messages to common.proto

- javascript-web/generate_protos.sh
This commit updates the list of files to compile with `protoc` to include `common.proto`, which contains messages shared among other protos. The preprocessing of protos specific to js-web is also updated to remove the package qualifiers from messages in `common.proto` in the same fashion that `permission_messages.Permissions` is being handled. Finally, a second `protoc` pass that was necessary to accommodate messages duplicated across protos has been removed, as the common messages are now shared instead of being re-declared in multiple places.
> chore: add common.proto to javascript-web

- proto/store.proto
New Store proto for Persistent Store
> feat: add store proto

- proto/global_admin.proto
- proto/store.proto
This commit prefixes the names of the messages in `store.proto` with the string "Store" to resolve name collisions in the Go SDK. In that SDK all of the messages end up living in the same namespace, so all of the request and response messages (e.g. `_GetRequest`) were colliding with the names in `cacheclient.proto`.
@honeyAcorn @anp13 I wanted to make sure you were both aware of and in agreement with this change. Please let me know if you see any issues or problems with renaming these.
> chore: add prefix to store service messages

- proto/global_admin.proto
Adds a new global API, used for generating account-scoped session tokens.
> feat: add account session token API

- proto/global_admin.proto
Use "role" instead of "membership_status" to match the mr2rs protos: https://github.com/momentohq/mr2rs/blob/main/proto/global_admin.proto
> fix: s/membership_status/role

- proto/global_admin.proto
Forgot to add `GetInvitattionsForUser` API. This commit adds that API.
> feat: add getInvitationsForUser API

- proto/cachepubsub.proto
Add a sequence_page field to topics. This will be in the discontinuities, the subscribe message, and the items next to the sequence number.
> chore: add topic sequence_page

- python/run-protoc.sh
Unable to upgrade the proto dependency in the python sdk without including the `common.proto` stuff in the python `momento_wire_types` package.
> fix: common.proto was missing from python momento_wire_types

- python/run-protoc.sh
Currently, upgrading the proto dependencies in the python sdk fails due to wrong import syntax (`import common_pb2 as common__pb2`) in `cachepubsub_pb2_grpc.py` file of `momento_wire_types`.
This was because we were missing the case where `common_pb2` (and other similar proto files) can be imported by `pb2_grpc.py` files too. This PR adds another substitution command for this situation.
> fix: python protoc postprocessing script needs to account for import statements in pb2_grpc.py files too

- rust/momento-protos/src/lib.rs
- rust/proto_generator/build.rs
Adds the leaderboard api proto to the rust crate.
> feat: add leaderboard api proto for rust

- proto/cacheclient.proto
This PR adds a New API `SortedSetUnionStore` that does the equivalent of Redis's `ZUNIONSTORE`
The union of elements in the source sorted sets is computed using the given weights and aggregate function, and the result is stored in the target set on which the api is invoked.
> feat: add SortedSetUnionStore api

- javascript/package-lock.json
- javascript/package.json
Bumps the `@grpc/grpc-js` dependency to the latest version (v1.13.1)
in the javascript project.
> chore: bump grpc-js to v1.13.1 in javascript

- javascript-web/package-lock.json
- javascript-web/package.json
- javascript/package-lock.json
- javascript/package.json
Because the JavaScript SDKs must also have the grpc
library (`@grpc/grpc-js` for node; `grpc-web` for web) installed, the
proto libraries here should declare grpc as a peer dependency, not
production dependency.
In the previous form as production dependencies, both the SDK and the
protos libraries install grpc as a dependency. Because we create grpc symbols
in the SDK to pass to objects from the protos library, and because the grpc library
performs an instanceof check on them, those symbols *must* be loaded from the
same copy of the grpc library. That is, the node module loader must be using the identical
(as in same files on the filesystem) in order for the instanceof check to pass.
In some situations, deduplication (same grpc library and same version) fails,
which causes the instanceof …
> chore: specify javascript grpc dependencies as peer dependencies

- javascript-web/package-lock.json
- javascript-web/package.json
- javascript/package-lock.json
- javascript/package.json
Similar to #315, protobuf should be a peer dependency in the
JavaScript projects. Since the SDKs install protobuf alongside grpc,
they are vulnerable to the same deduplication problem as we had with
grpc.
> chore: javascript(-web) should specify protobuf as a peer dependency

- java/build.gradle.kts
- kotlin/build.gradle.kts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1236
OSSRH is reaching end of life on June 30, 2025, so we migrated our namespace to Sonatype Central namespace and we must accordingly update the endpoints for where to push deployments.
> chore: replace OSSRH endpoint with Sonatype Central endpoint in java and kotlin scripts

- proto/protosocket/cache.proto
- proto/protosocket/common.proto
- rust/momento-protos/Cargo.toml
- rust/momento-protos/src/.gitignore
- rust/momento-protos/src/lib.rs
- rust/momento-protos/src/protosocket/.gitignore
- rust/proto_generator/build.rs
for reference: [example implementation in rust sdk](https://github.com/momentohq/client-sdk-rust/pull/473)
> feat: add protosocket-rpc cache protocols
