.github/workflows/push.yml, javascript/package-lock.json, javascript/package.json
Manually published this package to npm: https://www.npmjs.com/package/@momentohq/generated-types
This pr is to update the javascript-publish step so that it'll publish to npm instead of Artifactory.
Closes #35
=> chore: Publish JS package to npm

proto/cacheclient.proto, proto/controlclient.proto, proto/httpcache.proto
Added necessary lines to make it easier to copy over to https://github.com/momentohq/client-sdk-go when making proto changes
=> chore: add necessary lines to easily support updates to Go SDK

.github/workflows/pull_request.yml, .github/workflows/push.yml, rust/Cargo.toml
update the pull request to do a dry run release and the push workflow
to actually release to crates instead of artifactory.
=> feat: publish to crates.io

proto/cacheclient.proto
In line with the name proposal, this renames DictionaryGetAll* to
DictionaryFetch*.
=> feat: apply name proposal to DictionaryGetAll

.github/workflows/pull_request.yml, .github/workflows/push.yml, csharp/Momento.csproj
Add extended metadata for display on the public NuGet package repository.
=> chore: add metadata to csproj file for NuGet

.github/workflows/pull_request.yml, .github/workflows/push.yml, javascript-web/.gitignore, javascript-web/.npmignore, javascript-web/README.md, javascript-web/generate_protos.sh, javascript-web/index.ts, javascript-web/package-lock.json, javascript-web/package.json, javascript-web/tsconfig.json
Add grpc-web-text generated types so momento grpc can be used by
browsers. https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
Tested with a local package.json dependency from a create-react-app.
=> feat: javascript-webtext

proto/cacheclient.proto
https://github.com/momentohq/cacheservice/issues/883
=> feat: add list length api protos

.github/workflows/pull_request.yml
same commit as https://github.com/momentohq/client-sdk-javascript/pull/100/files
=> chore: add shared build step to ensure commits show up in releases

proto/cacheclient.proto
PR that captures incoming APIs: `list_concatenate_front` and `list_concatenate_back`
=> feat: update cacheclient with new list APIs

README.md
Includes links to the published packages for the protos for the
languages that are currently publishing them.
=> feat: improve README to provide more details about the protos

proto/cacheclient.proto
Adds protocols for a SetContains API, which can be used to query whether elements are members of a given Set.
=> feat: add SetContains API

javascript/README.md, javascript/generate_protos.sh
Adds `cachepubsub.proto` to the JavaScript build and README.
=> feat: generate pubsub code for javascript

java/build.gradle.kts
Declare the version outside any plugins to ensure it is consistent for each task. The fallback version is a SNAPSHOT which is unpublishable.
Skip all publishing related tasks if the required environment variables aren't defined.
=> fix: make the java version consistent for all tasks

proto/cacheclient.proto
=> feat: add ItemGetType & ItemGetTtl API

proto/cacheclient.proto
https://github.com/momentohq/mr2rs/pull/205
=> fix: indentation in the cacheclient proto

.github/workflows/push.yml, rust/momento-protos/src/.gitignore
shell escaping momentarily forgotten with the last pr
=> chore: fix github yml echos

csharp/Momento.Protos.csproj, javascript-web/generate_protos.sh, javascript/README.md, javascript/generate_protos.sh, proto/vectorindex.proto, python/run-protoc.sh, rust/proto_generator/build.rs
This new vectorindex proto just got copied from our internal mr2rs repo.
=> feat: add vectorindex proto

javascript/generate_protos.sh, javascript/package-lock.json, javascript/package.json
Was having trouble building the JS protos on my mac; this seems to fix for me.
=> fix: update js generate_protos.sh to use more recent npm packages for protoc

proto/vectorindex.proto
In sync with https://github.com/momentohq/mr2rs/pull/568
=> chore: rename AddItem to UpsertItem

proto/controlclient.proto
Adding new field for create vector index.
=> feat: expanding createIndex to support similarity metric

proto/vectorindex.proto
Adding `All` for search to retrieve all metatdata
=> feat: supporting retrieve all metadata

proto/cachepubsub.proto
Plumbing has already happened via https://github.com/momentohq/mr2rs/pull/599/files
This is just so that SDK team can use this
=> feat: add publisher id to Topics.

proto/vectorindex.proto
Add a fetch_vector flag for Search request, if it's true, return the vector.
Original issue: https://github.com/momentohq/mr2rs/issues/628
=> feat: add fetch_vector flag for search

proto/vectorindex.proto
We remove the whole flag and create a new API.
=> fix: remove optional for SearchHit Vector

proto/vectorindex.proto
We are adding search threshold (radius) to filter the search results.
=> feat: add search radius to filter results

proto/vectorindex.proto
This will allow us to get item by specifying all id. 
We do GetItemBatch API first. 
Then will have another PR to do the GetItemAndFetchVectorsBatch later.
=> feat: GetItemBatch API proto

proto/vectorindex.proto
=> chore: allow GetItemBatch api in rpc calls

proto/webhook.proto
This reverts commit 0a017672a5c61948aded3b120f579c497dd31ed0.
=> feat: revert secrets in ListWebhooksResponse

proto/vectorindex.proto
CountItems allows user to get `number of items` by providing index name as an input.
=> feat: CountItems API

proto/vectorindex.proto
changing response type from u32 to u64
=> chore: change count_items response from u32 to u64

csharp/Momento.Protos.csproj
chore: bump grpc dotnet version
=> chore: bump grpc dotnet version

proto/common.proto, proto/vectorindex.proto, proto/webhook.proto
This commit adds language-specific options to new proto files that were missing them.
=> chore: add standard language options to new proto files

proto/store.proto
https://gomomento.slack.com/archives/C04UUBXCL3H/p1723660007092109?thread_ts=1723504815.981519&channel=C04UUBXCL3H&message_ts=1723660007.092109
=> fix: update retry_disposition enum value to 'unknown'

proto/global_admin.proto
- Add "SetAccountName" api to global_admin proto. 
Part of https://github.com/momentohq/dev-eco-issue-tracker/issues/1006
=> feat: add SetAccountName api

proto/global_admin.proto
Console now uses the new InviteMember flow, meaning that this is no longer relevant.
=> chore: remove AddMember api

proto/leaderboard.proto
=> chore: remove cache from body. cache will be read from headers

javascript-web/generate_protos.sh, proto/cacheclient.proto, proto/common.proto
New version of https://github.com/momentohq/client-protos/pull/311 based on recent discussions.
Now updated to do conditional sets based on value hashes.
=> feat: new apis to check-and-set an item based on a hash

proto/function.proto, proto/function_types.proto
Port the function proto changes back to here.
=> chore: update function protos as we implement
